/**
 * notifications.test.ts
 *
 * Pure-function tests for the notification business logic.
 * HTTP-layer tests require a Clerk-mocked Express app — those are marked
 * as todos below. The pure-function layer is where the real invariants live.
 */

import { describe, it, expect } from "vitest";

// ── Serializer shape ──────────────────────────────────────────────────────────

/**
 * Mirrors serializeNotification from routes/notifications.ts.
 */
function serializeNotification(n: {
  id: string;
  type: string;
  title: string;
  body: string;
  positionId: string | null;
  read: boolean;
  createdAt: Date;
}) {
  return {
    id: n.id,
    type: n.type,
    title: n.title,
    body: n.body,
    position_id: n.positionId ?? null,
    read: n.read,
    created_at: n.createdAt.toISOString(),
  };
}

const BASE_NOTIFICATION = {
  id: "notif-uuid-1",
  type: "stale_positions",
  title: "3 stale positions need attention",
  body: "3 positions have not been updated in over 180 days.",
  positionId: null,
  read: false,
  createdAt: new Date("2025-01-15T10:00:00Z"),
};

describe("serializeNotification — output shape", () => {
  it("maps all fields correctly", () => {
    expect(serializeNotification(BASE_NOTIFICATION)).toEqual({
      id: "notif-uuid-1",
      type: "stale_positions",
      title: "3 stale positions need attention",
      body: "3 positions have not been updated in over 180 days.",
      position_id: null,
      read: false,
      created_at: "2025-01-15T10:00:00.000Z",
    });
  });

  it("converts positionId → position_id correctly", () => {
    const withPos = { ...BASE_NOTIFICATION, positionId: "pos-uuid-99" };
    expect(serializeNotification(withPos).position_id).toBe("pos-uuid-99");
  });

  it("null positionId serializes as null not undefined", () => {
    expect(serializeNotification(BASE_NOTIFICATION).position_id).toBeNull();
  });

  it("created_at is an ISO 8601 string", () => {
    const result = serializeNotification(BASE_NOTIFICATION);
    expect(result.created_at).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it("read flag is preserved as-is", () => {
    expect(serializeNotification({ ...BASE_NOTIFICATION, read: true }).read).toBe(true);
    expect(serializeNotification({ ...BASE_NOTIFICATION, read: false }).read).toBe(false);
  });

  it("exposes exactly the expected keys — no extras, no missing", () => {
    const keys = Object.keys(serializeNotification(BASE_NOTIFICATION)).sort();
    expect(keys).toEqual(
      ["body", "created_at", "id", "position_id", "read", "title", "type"].sort(),
    );
  });
});

// ── Notification types ────────────────────────────────────────────────────────

describe("notification type values", () => {
  const VALID_TYPES = ["stale_positions", "review_queue", "sync_error", "general"];

  it("all expected notification types are non-empty strings", () => {
    for (const t of VALID_TYPES) {
      expect(typeof t).toBe("string");
      expect(t.length).toBeGreaterThan(0);
    }
  });

  it("stale_positions and review_queue are auto-generated types (idempotent on regenerate)", () => {
    // These are the types wiped + regenerated on each POST /notifications/generate call.
    // Verifying they match the route implementation.
    const autoGeneratedTypes = new Set(["stale_positions", "review_queue"]);
    expect(autoGeneratedTypes.has("stale_positions")).toBe(true);
    expect(autoGeneratedTypes.has("review_queue")).toBe(true);
    // sync_error is user-triggered, not auto-generated
    expect(autoGeneratedTypes.has("sync_error")).toBe(false);
  });
});

// ── Preferences defaults ──────────────────────────────────────────────────────

describe("notification preferences — default values", () => {
  /** Mirrors the DB column defaults in lib/db/src/schema/notifications.ts */
  const DEFAULT_PREFS = {
    staleAlerts: true,
    reviewQueueAlerts: true,
    syncErrorAlerts: true,
  };

  it("stale alerts are on by default", () => {
    expect(DEFAULT_PREFS.staleAlerts).toBe(true);
  });

  it("review queue alerts are on by default", () => {
    expect(DEFAULT_PREFS.reviewQueueAlerts).toBe(true);
  });

  it("sync error alerts are on by default", () => {
    expect(DEFAULT_PREFS.syncErrorAlerts).toBe(true);
  });
});

// ── Stale count notification message logic ────────────────────────────────────

describe("stale position notification — message pluralisation", () => {
  function buildStaleTitle(count: number): string {
    return `${count} stale position${count > 1 ? "s" : ""} need attention`;
  }

  function buildStaleBody(count: number): string {
    return (
      `${count} position${count > 1 ? "s have" : " has"} not been updated in ` +
      `over 180 days and may require re-evaluation. ` +
      `Review the Intelligence › Stale Positions report.`
    );
  }

  it("singular form for count = 1", () => {
    expect(buildStaleTitle(1)).toBe("1 stale position need attention");
    expect(buildStaleBody(1)).toContain("1 position has not been updated");
  });

  it("plural form for count > 1", () => {
    expect(buildStaleTitle(3)).toBe("3 stale positions need attention");
    expect(buildStaleBody(3)).toContain("3 positions have not been updated");
  });
});

// ── HTTP-layer tests (todo — requires Clerk + DB mocks) ───────────────────────

describe("notifications HTTP-layer (blocked on Clerk/DB mocking)", () => {
  it.todo("GET /notifications returns 200 with array of serialized notifications");
  it.todo("GET /notifications?unread_only=true filters to unread only");
  it.todo("GET /notifications/count returns { unread: N }");
  it.todo("POST /notifications/generate creates stale_positions notification when stale positions exist");
  it.todo("POST /notifications/generate skips stale alert when staleAlerts pref is false");
  it.todo("POST /notifications/generate skips review_queue alert when reviewQueueAlerts pref is false");
  it.todo("POST /notifications/read-all marks all user notifications as read");
  it.todo("POST /notifications/:id/read marks one notification as read");
  it.todo("POST /notifications/:id/read returns 404 for unknown id");
  it.todo("GET /notifications/preferences returns defaults on first access (auto-creates row)");
  it.todo("PUT /notifications/preferences persists toggle changes");
});
